package conditionalDemo;

public class Finbnoci {

	public static void main(String[] args) {
		/* 0 1 1 2 3 5 8 13 21 34
		 fibnoci number are generated by adding the current number with previous one
		 0+1= 1; 1+1=2; 2+1=3; 3+2=5;........
		 take 3 variables initialize 2 variables with 0 and 1 and 3rd variable for iteration*/
		int n1 = 0,n2 = 1,n3,i, count=20;
		for (i=2; i<=count;i++)
		{
			n3=n1+n2;
			System.out.println(n1+" "+n3+" "+n2);
			n1=n2;
			n2=n3;
		}
	}

}
